format = """
$os\
$directory\
$git_branch\
$git_status\
$fill\
$conda\
$time\
$line_break\
$character\
"""

[os]
format = "[$symbol](bold white)"
disabled = false

[os.symbols]
Macos = "  "
Ubuntu = "  "
Windows = "  "

[directory]
truncation_length = 5
truncation_symbol = ".../"
truncate_to_repo = false
read_only = "󰌾 "
#home_symbol = " "

[git_branch]
style = "yellow"

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "red"
stashed = '\$${count}'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${count}"
conflicted = "=${count}"
deleted = "✘${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"

[fill]
symbol = " "

[conda]
#symbol = "\u{1f152} "

[time]
disabled = false
format = " [$time]($style)"
style = "purple"
time_format = "%T"
